### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by MirionQs** [MirionQs/yank-note-extension-math#1]
- [ ] 实现定理引用（编号可能变更，需要考虑如何实现）
- [ ] 实现目录增强（考虑注入标题规则获取相关信息后再构建目录，有空参考下 yn 实现）
- [ ] 将 KaTeX 增强配置文件移动到 yn 提供的数据目录（需要 api 进一步支持）
- [ ] 实现嵌入/移除嵌入的 KaTeX 配置（需要考虑如何实现）
- [ ] 解决多 \tag 初次渲染报错
- [x] 将 keepDisplayMode 移至 yn 设置
- [ ] 将共有样式移至独立的 scss 文件
